##  Numpy常用random随机函数汇总

官方文档地址：https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html


<img src="./other_files/numpy_random_functions.png" width="80%" style="margin-left:0px"/>

In [1]:
import numpy as np
np.random.seed(666)

### 1. rand(d0, d1, ..., dn)

返回数据在[0, 1)之间，具有均匀分布

In [2]:
np.random.rand(5)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796])

In [3]:
np.random.rand(3, 4)

array([[0.0127032 , 0.4135877 , 0.04881279, 0.09992856],
       [0.50806631, 0.20024754, 0.74415417, 0.192892  ],
       [0.70084475, 0.29322811, 0.77447945, 0.00510884]])

In [4]:
np.random.rand(2, 3, 4)

array([[[0.11285765, 0.11095367, 0.24766823, 0.0232363 ],
        [0.72732115, 0.34003494, 0.19750316, 0.90917959],
        [0.97834699, 0.53280254, 0.25913185, 0.58381262]],

       [[0.32569065, 0.88889931, 0.62640453, 0.81887369],
        [0.54734542, 0.41671201, 0.74304719, 0.36959638],
        [0.07516654, 0.77519298, 0.21940924, 0.07934213]]])

### 2. randn(d0, d1, ..., dn)
返回数据具有标准正态分布（均值0，方差1）

In [5]:
np.random.randn(5)

array([-1.20990266, -0.04618272, -0.44118244,  0.46953431,  0.44325817])

In [6]:
np.random.randn(3, 4)

array([[-1.66738875, -1.81731749, -1.39753916,  0.78392691],
       [-0.29129965,  0.67049043,  0.706931  ,  1.42965241],
       [-0.41407013, -1.32672274, -0.14880188,  0.34771289]])

In [7]:
np.random.randn(2, 3, 4)

array([[[ 0.61030791, -1.17532603,  0.82985368, -0.30236752],
        [-0.04327047,  0.06706965, -1.59102817,  0.01705112],
        [-1.87296591, -0.96457904, -0.00420389,  0.47495047]],

       [[-0.05421452,  0.89181355,  0.96866859,  0.6307865 ],
        [-0.89051986,  0.08227022, -0.07594056,  0.42969347],
        [ 0.11579967, -0.54443241,  0.02835341,  1.34408655]]])

### 3. randint(low[, high, size, dtype])

生成随机整数，包含low，不包含high  
如果high不指定，则从[0, low)中生成数字

In [8]:
np.random.randint(3)

2

In [9]:
np.random.randint(1, 10)

1

In [10]:
np.random.randint(10, 30, size=(5,))

array([27, 16, 25, 18, 18])

In [11]:
np.random.randint(10, 30, size=(2,3,4))

array([[[26, 19, 14, 21],
        [29, 25, 19, 21],
        [28, 12, 13, 19]],

       [[27, 27, 18, 27],
        [16, 24, 16, 19],
        [21, 20, 19, 14]]])

### 4. random([size])	
生成[0.0, 1.0)的随机数

In [12]:
np.random.random(5)

array([0.95858105, 0.66579831, 0.84015904, 0.14691185, 0.14394403])

In [13]:
np.random.random(size=(3,4))

array([[0.30843116, 0.37016398, 0.31852964, 0.56240025],
       [0.4640979 , 0.80066784, 0.78735522, 0.84323067],
       [0.68824287, 0.31854825, 0.93794112, 0.40711455]])

In [14]:
np.random.random(size=(2,3,4))

array([[[0.75336448, 0.5065076 , 0.8242313 , 0.48603164],
        [0.17872445, 0.79322194, 0.13924006, 0.71347858],
        [0.38300909, 0.70410853, 0.82867258, 0.58154578]],

       [[0.38693726, 0.39648041, 0.15039198, 0.08835265],
        [0.80002064, 0.86760024, 0.88654384, 0.76250128],
        [0.2158761 , 0.60311702, 0.17688438, 0.15759693]]])

### 5. choice(a[, size, replace, p])
a是一维数组，从它里面生成随机结果


In [15]:
# 这时候，a是数字，则从range(5)中生成，size为3
np.random.choice(5, 3)

array([4, 2, 4])

In [16]:
np.random.choice(5, (2,3))

array([[3, 3, 2],
       [4, 0, 2]])

In [17]:
# 这时候，a是数组，从里面随机取出数字
np.random.choice([2, 3, 6, 7, 9], 3)

array([3, 9, 6])

In [18]:
np.random.choice([2, 3, 6, 7, 9], (2,3))

array([[7, 9, 2],
       [6, 9, 6]])

### 6. shuffle(x)	
把一个数组x进行随机排列

In [19]:
a = np.arange(10)
np.random.shuffle(a)
a

array([7, 2, 3, 6, 1, 9, 8, 4, 0, 5])

In [20]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
# 如果数组是多维的，则只会在第一维度打散数据
np.random.shuffle(a)
a

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

### 7. permutation(x)
把一个数组x进行随机排列，或者数字的全排列

In [22]:
# 这时候，生成range(10)的随机排列
np.random.permutation(10)

array([1, 5, 3, 0, 2, 4, 7, 9, 6, 8])

In [23]:
# 这时候，在第一维度进行打散
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# 注意，这里不会更改原来的arr，会返回一个新的copy
np.random.permutation(arr)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [25]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 8. normal([loc, scale, size])
按照平均值loc和方差scale生成高斯分布的数字

In [26]:
np.random.normal(1, 10, 10)

array([ 10.80291099,  13.10516541, -23.0910327 ,  14.49409934,
        -6.290444  ,  -9.42735397,  -2.28926527, -13.71681338,
       -13.04515295,  -5.32726848])

In [27]:
np.random.normal(1, 10, (3,4))

array([[  3.00692005,   2.62218924,   2.60682046,  13.11370959],
       [-12.63957919,   2.30310161,  13.59875359,  10.79500364],
       [ 18.37674494, -13.17309889,  -3.82004022, -20.47660377]])

### 9. uniform([low, high, size]) 	
在[low, high)之间生成均匀分布的数字

In [ ]:
np.random.uniform(1, 10, 10)

In [ ]:
np.random.uniform(1, 10, (3,4))

### 实例：对数组加入随机噪声

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# 绘制sin曲线
x = np.linspace(-10, 10, 100)
y = np.sin(x)
plt.plot(x, y)
plt.show()

In [ ]:
# 加入噪声
x = np.linspace(-10, 10, 100)
y = np.sin(x) + np.random.rand(len(x))
plt.plot(x, y)
plt.show()